server:
  port: 8083

logging:
  level:
    sql: trace

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: admin

  flyway:
    url: jdbc:postgresql://localhost:5432/test?ssl=false
    user: admin
    password: admin
    schemas:
      - "public"
    locations:
      - classpath:/migrations/